import Head from "next/head";
import { useRouter } from "next/router"

import CharactersList from "@/components/CharactersList"
import Header from "@/components/Header"

import { useState } from "react";

export default function CharactersPage() {

	const router = useRouter();
	const { id } = router.query;

	if (!router.isReady) return <div>Loading...</div>

	console.log("Qui dovrei recuperare i dati dall'api /characters/id ");

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<h2>Pagina dettagli</h2>
			<h3>ID: {id}</h3>

		</>
	);
}
