import Head from "next/head";

// import Componente from "@/components/Componente"
// import UseEffectTest from "@/components/UseEffectTest"
import CharactersList from "@/components/CharactersList"
import Header from "@/components/Header"

// import data from "@/data/data";

import { useState } from "react";
import Componente from "@/components/Componente";

export default function CharactersPage() {



	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/*
      <Componente proprieta={42} />
      <UseEffectTest />
      */}
			<Header />

			<Componente />
			<CharactersList />

		</>
	);
}
