import Head from "next/head";
import Header from "@/components/Header"
import { useState } from "react";
import { getUser } from "@/services/mockUsers"

export default function PromisePage() {

	const [esito, setEsito] = useState(null);
	const [sceltaUtente, setSceltaUtente] = useState("testa");

	const [users, setUsers] = useState([]);

	function gioca() {

		setEsito(null);
		setSceltaUtente("testa");
		console.log("Inizio partita");

		//operazione asincrona
		lanciaMoneta(sceltaUtente).then(risultato => {
			console.log("Esito partita: ", risultato);
			setEsito(risultato);
		}).catch(err => {
			console.error("Esito partita: ", err);
			setEsito(err);
		})

		// stampa esito
	}

	function lanciaMoneta(sceltaUtente) {
		return new Promise((resolve, reject) => {

			console.log(`Utente sceglie ${sceltaUtente}. Sto lanciando la moneta...`);

			setTimeout(() => {

				const valore = Math.round(Math.random());
				const risultato = valore == 0 ? "testa" : "croce";

				if (risultato == sceltaUtente) {
					resolve("vittoria")
				} else {
					reject("sconfitta");
				}

			}, 1500);

		});
	}

	function getDatiEsterni() {

		getUser(2).then(utente => {
			console.log("Trovato l'utente", utente);
		}).catch(err => {
			console.error("Qualcosa è andato storto: ", err.message);
		});
	}

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<h2>Promessa: lancio moneta</h2>
			<h3>L'utente sceglie sempre testa</h3>
			<p>Esito: {esito}</p>
			<button onClick={gioca}>Lancia moneta</button>

			<div>
				<h2>Lista utenti</h2>
				<button onClick={getDatiEsterni}>Recupera dati</button>
				<ul>
					{users.map(utente => <li>{utente.id}. {utente.name}</li>)}
				</ul>
			</div>

		</>
	);
}
