import Head from "next/head";
import Header from "@/components/Header"
import { useState } from "react";
import { getUser, getPost, getQualcosa } from "@/services/mockUsers"

export default function PromisePage() {

	const [esito, setEsito] = useState(null);
	const [sceltaUtente, setSceltaUtente] = useState("testa");

	const [users, setUsers] = useState([]);

	function gioca() {

		setEsito(null);
		setSceltaUtente("testa");
		console.log("Inizio partita");

		//operazione asincrona
		lanciaMoneta(sceltaUtente).then(risultato => {
			console.log("Esito partita: ", risultato);
			setEsito(risultato);
		}).catch(err => {
			console.error("Esito partita: ", err);
			setEsito(err);
		})

		// stampa esito
	}

	function lanciaMoneta(sceltaUtente) {
		return new Promise((resolve, reject) => {

			console.log(`Utente sceglie ${sceltaUtente}. Sto lanciando la moneta...`);

			setTimeout(() => {

				const valore = Math.round(Math.random());
				const risultato = valore == 0 ? "testa" : "croce";

				if (risultato == sceltaUtente) {
					resolve("vittoria")
				} else {
					reject("sconfitta");
				}

			}, 1500);

		});
	}

	function recuperaDati_Then() {
		getUser(2).then(utente => {
			console.log("Trovato l'utente", utente);

			getPost(utente.postId).then(post => {
				console.log("Trovato anche il post dell'utente", post);
			}).catch(err => {
				console.error("Qualcosa è andato storto per POST: ", err.message);
			});

		}).catch(err => {
			console.error("Qualcosa è andato storto per USER: ", err.message);
		});

		console.log("Dopo il then, eseguito subito, prima dei dati");
	}

	async function recuperaDati_SingoloCatch() {
		const post = null;

		try {
			const utente = await getUser(2);
			console.log("Trovato utente", utente);
			const post = await getPost(utente.postId);
			console.log("Trovato anche il post", post);
		} catch {
			console.error("Qualcosa è andato storto");
		}

		console.log("Qui tutto bene");

		return post;
	}

	async function recuperaDati_CatchSeparati() {
		let utente = null;
		let post = null;

		try {
			utente = await getUser(2);
			console.log("Trovato utente", utente);
		} catch (error) {
			console.error("Errore nel recuperare l'utente")
			// throw new Error("Impossibile recuperare l'utente");
		}

		try {
			post = await getPost(utente.postId);
			console.log("Trovato anche il post", post);
		} catch (error) {
			console.error("Errore nel recuperare il post")
		}

		console.log("==>", utente, post);
	}

	async function recuperaDati() {
		try {
			const utente = await getUser(2);
			console.log("Trovato utente", utente);

			const post = await getPost(utente.postId);
			console.log("Trovato anche il post", post);

		} catch (error) {
			console.error(`Errore nel recuperare dati`, error.message)
		}
	}

	async function gestisciClick() {

		//...fai cose...

		// recuperaDati().then(console.log);
		console.log(await recuperaDati_CatchSeparati());

		//...fai cose...

	}

	function calcolaQuadrato() {

		const quadrato3 = getQualcosa(3);
		console.log(quadrato3);

		try {
			const quadrato42 = getQualcosa(42);
			console.log(quadrato42);
		} catch (error) {
			console.error("qualcosa è andato storto", error.message)
		}

		console.log("altro ancora");
	}

	function getMultipleUsers() {

		// const chiamate = [ false, false ];
		// const risultati = [];

		// const bob = getUser(1).then(utente => {
		// 	console.log("dati ottenuti per 1", utente);
		// 	chiamate[0] = true;
		// 	risultati.push(utente);
		// });

		// const alice = getUser(2).then(utente => {
		// 	console.log("dati ottenuti per 2", utente);
		// 	chiamate[1] = true;
		// 	risultati.push(utente);
		// });

		const promesse = [
			getUser(1),
			getUser(2)
		];

		const x = Promise.all(promesse);

		x.then(dati => {
			const [bob, alice] = dati;

			console.log(bob);
			console.log(alice);
		}).catch(err => {
			console.error("errore: ", err);
		});

	}

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<h2>Promessa: lancio moneta</h2>
			<h3>L'utente sceglie sempre testa</h3>
			<p>Esito: {esito}</p>
			<button onClick={gioca}>Lancia moneta</button>

			<div>
				<h2>Lista utenti</h2>
				<button onClick={recuperaDati}>Recupera dati</button>
				<ul>
					{users.map(utente => <li>{utente.id}. {utente.name}</li>)}
				</ul>
			</div>

			<button onClick={calcolaQuadrato}>Calcola quadrato</button>
			<button onClick={getMultipleUsers}>Recupera utenti</button>

		</>
	);
}
